services:
  api:
    build:
      context: ../..
      dockerfile: docker/build/DockerFile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: Host=db;Port=5432;Database=expensetrackerdb;Username=expensetracker;Password=expensetrackerpw
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: expensetracker_postgres
    restart: always
    environment:
      POSTGRES_USER: expensetracker
      POSTGRES_PASSWORD: expensetrackerpw
      POSTGRES_DB: expensetrackerdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
